### PR TITLE
v4 documentation page

### LINKED ISSUE #27: v4.x Documentation

### PR DESCRIPTION
**Pull request by Eomm**
closes #27 

## how to test it

1. install GH CLI https://cli.github.com/
2. install the repo as described in the readme
3. run `npm run build:website`
4. run `npm start` to see the documentation

## features

- [x] it supports legacy `/docs/latest` links
- [x] every v4's minor version has its own documentation
- [x] the left menu is equal to the previous website
- [x] all the pages are visible correctly
- [x] all links are working
- [x] the edit page button works
- [x] it supports `/docs/master` links. I will add a redirect to `/docs/latest` or `/docs/next`

### CODE REVIEW

**Comment by Eomm** [comment]
Hi, would you @fanciulli @HassanBahati like to take a look at this PR?

There are some todos that I will address in follow-up PRs (eg: integrating the scripts to generate the `plugin.json`, `benchmark.json` and `members.json`)

**Comment by fanciulli** [comment]
Hello @Eomm ,

i found the following:

1. During `npm run build:website` i got the following. Don't know if it is an error, reporting anyway
```

[10:48:52.519] DEBUG (87758): Generated categories
[10:48:52.522] INFO (87758): Processing 4.9.2
[10:48:52.522] DEBUG (87758): Coping /Users/massimilianofanciulli/Sviluppo/website-next/scripts/releases/4.9.2/docs/.
[10:48:52.548] DEBUG (87758): Copied to /Users/massimilianofanciulli/Sviluppo/website-next/versioned_docs/version-v4.9.x
[10:48:52.548] DEBUG (87758): Created sidebar /Users/massimilianofanciulli/Sviluppo/website-next/versioned_sidebars/version-v4.9.x-sidebars.json
[10:48:52.552] DEBUG (87758): Generated categories
AssertionError [ERR_ASSERTION]: 1
    at getDocFolders (/Users/massimilianofanciulli/Sviluppo/website-next/scripts/process-releases.js:119:9)
    at getDocFolders.next (<anonymous>)
    at processReleases (/Users/massimilianofanciulli/Sviluppo/website-next/scripts/process-releases.js:41:14) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: 0,
  expected: true,
  operator: '=='
}
[10:48:52.556] INFO (87758): Error processing release [none] because 1
[10:48:52.560] DEBUG (87758): Coping /Users/massimilianofanciulli/Sviluppo/website-next/versioned_docs/version-v4.11.x/.
[10:48:52.594] DEBUG (87758): Copied to /Users/massimilianofanciulli/Sviluppo/website-next/versioned_docs/version-latest
[10:48:52.595] INFO (87758): Wrote 12 versions to versions.json
[10:48:53.127] INFO (87758): Done
```

2. Docusarus found broken links (again, it could be because of incomplete PR): 
```
[WARNING] Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

It looks like some of the broken links we found appear in many pages of your site.
Maybe those broken links appear on all pages through your site layout?
We recommend that you check your theme configuration for such links (particularly, theme navbar and footer).
Frequent broken links are linking to:
- ./Validation-and-Serialization.md
- ./Type-Providers.md
- ./HTTP2.md
- Logging.md
- ./Server.md#register
- ./Logging.md

```

Except for the above, the work LGTM!

**Comment by HassanBahati** [comment]
hi @Eomm i installed GH CLI https://cli.github.com/  then ran `npm run build:website` this was the result

```sh
[INFO] [en] Creating an optimized production build...
[ERROR] Unable to build website for locale en.
[ERROR] Error: It is not possible to use docs without any version. No version is included because you have requested to not include /home/edna/Desktop/bahati/Workspace/fastify/website-next/docs through "includeCurrentVersion: false", while the versions file is empty/non-existent.
    at readVersionNames (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/plugin-content-docs/lib/versions/files.js:95:15)
    at async readVersionsMetadata (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/plugin-content-docs/lib/versions/index.js:146:29)
    at async Object.pluginContentDocs [as plugin] (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/plugin-content-docs/lib/index.js:32:30)
    at async initializePlugin (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/plugins/init.js:83:32)
    at async Promise.all (index 0)
    at async initPlugins (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/plugins/init.js:91:21)
    at async loadPlugins (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/plugins/index.js:26:21)
    at async load (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/index.js:76:58)
    at async buildLocale (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/commands/build.js:84:19)
    at async tryToBuildLocale (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/commands/build.js:38:20)
[INFO] Docusaurus version: 2.2.0
Node version: v16.16.0
```

then moved to run `npm start` this was the result

```sh
[INFO] Starting the development server...
[ERROR] Error: It is not possible to use docs without any version. No version is included because you have requested to not include /home/edna/Desktop/bahati/Workspace/fastify/website-next/docs through "includeCurrentVersion: false", while the versions file is empty/non-existent.
    at readVersionNames (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/plugin-content-docs/lib/versions/files.js:95:15)
    at async readVersionsMetadata (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/plugin-content-docs/lib/versions/index.js:146:29)
    at async Object.pluginContentDocs [as plugin] (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/plugin-content-docs/lib/index.js:32:30)
    at async initializePlugin (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/plugins/init.js:83:32)
    at async Promise.all (index 0)
    at async initPlugins (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/plugins/init.js:91:21)
    at async loadPlugins (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/plugins/index.js:26:21)
    at async load (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/index.js:76:58)
    at async Command.start (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/commands/start.js:42:19)
[INFO] Docusaurus version: 2.2.0
Node version: v16.16.0
```

**Comment by Eomm** [comment]
Thanks for the feedback

> [10:48:52.556] INFO (87758): Error processing release [none] because 1

No, that error is not expected. I will fix it!

> Docusarus found broken links (again, it could be because of incomplete PR):

I saw those warnings, but docusaurus handled them by "understanding" which was the right target page (the logs should show the `resolved to` sentence).
Those links must be fixed in the main fastify repo - but we will fix only the latest version

**Comment by HassanBahati** [comment]
hi @Eomm i installed GH CLI https://cli.github.com/ tried running `npm run build:website`

```sh
[INFO] [en] Creating an optimized production build...
[ERROR] Unable to build website for locale en.
[ERROR] Error: It is not possible to use docs without any version. No version is included because you have requested to not include /home/edna/Desktop/bahati/Workspace/fastify/website-next/docs through "includeCurrentVersion: false", while the versions file is empty/non-existent.
    at readVersionNames (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/plugin-content-docs/lib/versions/files.js:95:15)
    at async readVersionsMetadata (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/plugin-content-docs/lib/versions/index.js:146:29)
    at async Object.pluginContentDocs [as plugin] (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/plugin-content-docs/lib/index.js:32:30)
    at async initializePlugin (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/plugins/init.js:83:32)
    at async Promise.all (index 0)
    at async initPlugins (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/plugins/init.js:91:21)
    at async loadPlugins (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/plugins/index.js:26:21)
    at async load (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/index.js:76:58)
    at async buildLocale (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/commands/build.js:84:19)
    at async tryToBuildLocale (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/commands/build.js:38:20)
[INFO] Docusaurus version: 2.2.0
Node version: v16.16.0
```

then tried running `npm start` 

```sh
[INFO] Starting the development server...
[ERROR] Error: It is not possible to use docs without any version. No version is included because you have requested to not include /home/edna/Desktop/bahati/Workspace/fastify/website-next/docs through "includeCurrentVersion: false", while the versions file is empty/non-existent.
    at readVersionNames (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/plugin-content-docs/lib/versions/files.js:95:15)
    at async readVersionsMetadata (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/plugin-content-docs/lib/versions/index.js:146:29)
    at async Object.pluginContentDocs [as plugin] (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/plugin-content-docs/lib/index.js:32:30)
    at async initializePlugin (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/plugins/init.js:83:32)
    at async Promise.all (index 0)
    at async initPlugins (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/plugins/init.js:91:21)
    at async loadPlugins (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/plugins/index.js:26:21)
    at async load (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/server/index.js:76:58)
    at async Command.start (/home/edna/Desktop/bahati/Workspace/fastify/website-next/node_modules/@docusaurus/core/lib/commands/start.js:42:19)
[INFO] Docusaurus version: 2.2.0
Node version: v16.16.0
```

**Comment by HassanBahati** [comment]
alright, let me try that

**Comment by Eomm** [comment]
> During npm run build:website i got the following. Don't know if it is an error, reporting anyway

Fixed, could you retry? - It will suggest to run `gh auth login`

**Comment by Eomm** [comment]
I need to merge this to push things forward - if any issues will rise, I will take care of them 👍🏽

**Pull request merged**
