### PR TITLE
Fix Broken benchmarks button

### PR DESCRIPTION
**Pull request by HassanBahati**
Bug fixes and new features should include tests and possibly benchmarks.

Contributors guide: https://github.com/fastify/fastify/blob/master/CONTRIBUTING.md

By making a contribution to this project, I certify that:

* (a) The contribution was created in whole or in part by me and I
  have the right to submit it under the open source license
  indicated in the file; or

* (b) The contribution is based upon previous work that, to the best
  of my knowledge, is covered under an appropriate open source
  license and I have the right under that license to submit that
  work with modifications, whether created in whole or in part
  by me, under the same open source license (unless I am
  permitted to submit under a different license), as indicated
  in the file; or

* (c) The contribution was provided directly to me by some other
  person who certified (a), (b) or (c) and I have not modified
  it.

* (d) I understand and agree that this project and the contribution
  are public and that a record of the contribution (including all
  personal information I submit with it, including my sign-off) is
  maintained indefinitely and may be redistributed consistent with
  this project or the open source license(s) involved.
-->

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by HassanBahati** [comment]
This pr fixes #18 , where there is a broken link to the benchmarks page.

cc: @mcollina @lachlancollins @Xhale1

**Review by Eomm — APPROVED** [review]
Thanks for the fix, it will be useful for the website we are going to build in the next weeks 🔝

**Comment by HassanBahati** [comment]
> Thanks for the fix, it will be useful for the website we are going to build in the next weeks 🔝

Thank you @Eomm ... excited for this website.

**Comment by HassanBahati** [comment]
@Eomm I also wanted to understand the goal we are achieving with this website...are we rebuilding [https://www.fastify.io/](https://www.fastify.io/) as a foundation for this one ?  Is to meant to have everything that is currently available in [https://www.fastify.io/](https://www.fastify.io/)

**Comment by Eomm** [comment]
All the info are here https://github.com/fastify/website-next/pull/16#issue-1490029318
I will set up a GH project soon 👍🏽

**Comment by HassanBahati** [comment]
> All the info are here [#16 (comment)](https://github.com/fastify/website-next/pull/16#issue-1490029318) I will set up a GH project soon 👍🏽

Thank you! Let me check it out. Will be waiting on the GH project 🥳

**Pull request merged**
